### ISSUE TITLE
PortableInfoboxes does not cooperate with the Popups extension

### ISSUE THREAD

**Issue by penguinstyles** [lkucharczyk/mediawiki-PortableInfobox#17]
The PortableInfoboxes extension causes Popups to display infobox information instead of the first few paragraphs of the page.

![image](https://user-images.githubusercontent.com/5971630/50412753-d38b5e00-07d7-11e9-8620-cdc1e4b6fb17.jpg)

Relevant links:
https://kingkiller.wiki/w/The_Name_of_the_Wind
https://kingkiller.wiki/w/The_Wise_Man%27s_Fear

**Comment by lkucharczyk** [comment]
Thanks for the report. f558c16a3df0dbedf41aa29f9df50738f031a0f7 should fix that, can you check it with `$wgPortableInfoboxUseHeadings` set to `false`?

**Comment by penguinstyles** [comment]
Yep, looks like that fixed it. Thanks for the quick response!

Are you planning on forking any other Wikia extensions? It would definitely help expedite the process of moving away from Wikia when needed.

**Comment by penguinstyles** [comment]
Oh, interestingly enough https://github.com/lkucharczyk/mediawiki-PortableInfobox/commit/f558c16a3df0dbedf41aa29f9df50738f031a0f7 now prevents any image used in the PI from being displayed in the Popup. 

![image](https://user-images.githubusercontent.com/5971630/50427474-56afc100-0877-11e9-9e06-ba84e7d7e48e.png)

**Comment by lkucharczyk** [comment]
Are you sure, it worked before with PIs? It seems that pi images aren't passed to the PageImages extension at all (unless specific hooks are fired, when we pass them via `<gallery>` or `<tabber>`). I'll see, what I can do about it tommorow.

Sorry, but I'm planning to port any other Wikia extension right now.

**Comment by lkucharczyk** [comment]
3dcb820a08f1ed03a95426cc723be0ea450625b3 (issue-17 branch) should fix that, can you check it as well?

**Comment by lkucharczyk** [comment]
It seems that extracting images works fine now (https://kingkiller.wiki/w/api.php?action=query&prop=pageimages&titles=Ambrose%20Jakis%7CKvothe%7CSimmon&format=jsonfm) and they appear in the popups now. @penguinstyles Is there still any problem with them or can I close this and merge those changes to the master branch?

**Comment by penguinstyles** [comment]
Yes, sorry! https://github.com/lkucharczyk/mediawiki-PortableInfobox/commit/3dcb820a08f1ed03a95426cc723be0ea450625b3 fixed the issue. Thanks for your help.
