### ISSUE TITLE
`ObjectCache::getMainWANInstance()` is undefined on my instance

### ISSUE THREAD

**Issue by Atlas48** [lkucharczyk/mediawiki-PortableInfobox#27]
When I try to save pages on my hosted server, it fails, after analyzing the output via `$wgDebugComments=true;` on my sandbox page, I have got the following output

```
[XoNDVNalgmHIvdt2O67zkwAAAW4] /wiki/index.php?title=Sandbox&amp;action=submit   Error from line 29 of /home/ldysvmfy/domains/astralscape.wtf/public_html/wiki/extensions/PortableInfobox/includes/services/PortableInfoboxDataService.php: Call to undefined method ObjectCache::getMainWANInstance()
```

This appears to be a bug, so thusly I am submitting it to here, rather than stackoverflow.

**Comment by lkucharczyk** [comment]
Already fixed in #23
