### ISSUE TITLE
Error with MW 1.34.2

### ISSUE THREAD

**Issue by klaudiadottv** [lkucharczyk/mediawiki-PortableInfobox#33]
When i try to create a Portable Infobox (copied from Wikia) i get this error message:

> [XxoI1jKv2vJsVhZVaLmhyAAAANg] 2020-07-23 22:01:59: Fatal exception of type "Error"

Extension is cloned from master a few mins ago.

MediaWiki: 1.34.2
PHP: 7.3.19 (cgi-fcgi)

Extensions:
- CodeEditor
- VisualEditor
- WikiEditor
- NoTitle
- ParserFunctions
- Portable Infobox
- Bootstrap

**Comment by UnknownSkyrimPasserby** [comment]
This patch fixes it: https://github.com/lkucharczyk/mediawiki-PortableInfobox/pull/32

**Comment by lkucharczyk** [comment]
Fixed in 05e55672a62edfc9573d6c7a00bd34ca240a4ec5
