### ISSUE TITLE
Error with new instance of MW 1.34.2 (Clean install)

### ISSUE THREAD

**Issue by l1ghtsword** [lkucharczyk/mediawiki-PortableInfobox#34]
I pulled the extension from your Git master branch, confirmed the file access permissions should be readable and added the include to the LocalSettings.php.

MW does not crash on regular page loading but is unable to save any page calling \<infobox\>.
Doing so generates this error. (Logs and details below)
![Capture](https://user-images.githubusercontent.com/59493580/93369460-67f3ea80-f81d-11ea-9737-9de906179c1b.PNG)
<br><br>
**Error in Apache Log:**
```
"16:42:23.558469 2020] [php7:error] [pid 10078] [client {SOURCE IP}] PHP Fatal error: Class 'LightnCandy\\LightnCandy' not found in
/www/{myWikiURL}/extensions/PortableInfobox/includes/services/PortableInfoboxRenderService.php on line 14, referer: https://{MyWikiURL}/index.php?title=Template:TestInfoBox&action=edit
```
<br><br>
**Special:versions**
```
MediaWiki | 1.34.2
PHP | 7.2.33 (apache2handler)
MySQL | 5.7.29
ICU | 65.1
Lua | 5.1.5
```
<br><br>
**Installed Extensions:**
`CiteThisPage, Replace Text, WikiEditor, Portable Infobox, Scribunto, PDF Handler, ConfirmEdit, SpamBlacklist, TitleBlacklist, PageImages`
<br><br>
**Installed Libs:**
`christian-riesen/base32, Ver:1.3.2, - composer/semver, Ver:1.5.0, - cssjanus/cssjanus, Ver:1.3.0, - guzzlehttp/guzzle, Ver:6.3.3, - guzzlehttp/promises, Ver:1.3.1, - guzzlehttp/psr7, Ver:1.5.2, - jakobo/hotp-php, Ver:1.0.1, - liuggio/statsd-php-client, Ver:1.0.18, - oojs/oojs-ui, Ver:0.34.1, - pear/console_getopt, Ver:1.4.2, - pear/mail, Ver:1.4.1, - pear/mail_mime, Ver:1.10.2, - pear/net_smtp, Ver:1.8.1, - pear/net_socket, Ver:1.2.2, - pear/pear-core-minimal, Ver:1.10.9, - pear/pear_exception, Ver:1.0.0, - pleonasm/bloom-filter, Ver:1.0.2, - psr/container, Ver:1.0.0, - psr/http-message, Ver:1.0.1, - psr/log, Ver:1.0.2, - ralouphie/getallheaders, Ver:2.0.5, - wikimedia/assert, Ver:0.2.2, - wikimedia/at-ease, Ver:2.0.0, - wikimedia/avro, Ver:1.9.0, - wikimedia/base-convert, Ver:2.0.0, - wikimedia/cdb, Ver:1.4.1, - wikimedia/cldr-plural-rule-parser, Ver:1.0.0, - wikimedia/composer-merge-plugin, Ver:1.4.1, - wikimedia/html-formatter, Ver:1.0.2, - wikimedia/ip-set, Ver:2.1.0, - wikimedia/ip-utils, Ver:1.0.0, - wikimedia/less.php, Ver:1.8.0, - wikimedia/object-factory, Ver:2.1.0, - wikimedia/password-blacklist, Ver:0.1.4, - wikimedia/php-session-serializer, Ver:1.0.7, - wikimedia/purtle, Ver:1.0.7, - wikimedia/relpath, Ver:2.1.1, - wikimedia/remex-html, Ver:2.1.0, - wikimedia/running-stat, Ver:1.2.1, - wikimedia/scoped-callback, Ver:3.0.0, - wikimedia/timestamp, Ver:3.0.0, - wikimedia/utfnormal, Ver:2.0.0, - wikimedia/wait-condition-loop, Ver:1.0.1, - wikimedia/wrappedstring, Ver:3.0.1, - wikimedia/xmp-reader, Ver:0.6.3, - zordius/lightncandy, Ver:0.23`

**Comment by lkucharczyk** [comment]
Fixed in 05e55672a62edfc9573d6c7a00bd34ca240a4ec5
